eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


microservice:
  stock-service:
    endpoint:
      uri: http://localhost:8091/api/v1/stock
  product-service:
    endpoint:
      uri: http://localhost:8090/api/v1/produit
